### ISSUE TITLE
[BUG]Changing posture from the character sheet sometimes causes posture changes to fail

### ISSUE THREAD

**Issue by Klasodeth** [crnormand/gurps#1820]
Under certain circumstances with tokens that have Link Actor Data enabled, multiple posture changes done from the character sheet result in an error that prevents further posture changes.

Steps to reproduce (this assumes the character starts in the Standing posture:
1. Open character sheet
2. Within the character sheet, switch from Standing to any other posture (ex. Lying Down)
3. Switch to Standing posture
4. Switch to any other posture except for the posture selected in Step 2 (ex. Kneeling)
5. Switch to Standing posture

Upon selecting Standing for the second time, the error seen in the attached screenshot appears:

![Foundry Error](https://github.com/crnormand/gurps/assets/8529362/8046c189-f4f8-48cc-a00b-6d0dd86e1d27)

Once this error occurs, pressing F5 to refresh the scene clears the error state (until broken again by further posture changes from the character sheet. Posture changes done from the Assign Status Effects menu appear to be unaffected.

Foundry Virtual Tabletop Version 11 Stable Build 304
GURPS 4e Game Aid (Unofficial) 0.16.1

**Comment by mjeffw** [comment]
I couldn't get this to reproduce the problem. I just fixed another related problem, could you update GGA to 0.16.2 when it comes out and retest?

**Comment by Klasodeth** [comment]
I've updated to Foundry v11 Build 305 and GGA 0.16.3 and still get the same behavior, though the error is slightly different now. Here's the latest error:

![Foundry Error 2](https://github.com/crnormand/gurps/assets/8529362/c7a507b2-c2be-455f-97c2-d673846b52bf)

This occurs even in a newly created scene with all modules disabled. As before, this only occurs with tokens that have 'Link Actor Data' enabled. I don't have this problem with any token that does not have 'Link Actor Data' enabled,

**Comment by cirelli** [comment]
I have this problem too.
it also happens when using auto Reeling/Tired. When the system apply Reeling/Tired status, is impossible to remove it.
